name: Build Drivers Friend APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Encontrar e Buildar
        run: |
          # Encontra a pasta onde está o projeto Android
          GRADLE_DIR=$(find . -name build.gradle -not -path "*/android-sdk/*" | head -n 1 | xargs dirname)
          echo "Entrando na pasta: $GRADLE_DIR"
          cd "$GRADLE_DIR"
          # Usa o Gradle instalado pelo GitHub em vez do arquivo que deu erro
          gradle assembleRelease
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: "**/build/outputs/apk/release/*.apk"
          
